version: '3.8'
services:
  scraper:
    build: .
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - LOG_DIR=/app/logs
      - LOG_FILENAME=scraper.log